// svelte/auth/src/routes/profile/+page.svelte
<script>
	export let data;
</script>

<div class="card">
	<div class="avatar is-size-x-large"><span class="icon-user" /></div>
	<h1 class="heading-level-5">{data.account?.name}</h1>
	<a href="/" class="button is-secondary u-margin-block-start-16" type="button">Go back</a>
</div>

<style>
	.card {
		width: 15rem;
		max-width: calc(100vw - 2rem);

		display: flex;
		flex-direction: column;
		align-items: center;
	}
</style>

// react/auth/src/routes/profile.tsx
import { useAccount } from "@/context/account";
import React from "react";
import { Link, Navigate } from "react-router-dom";
import styles from "./profile.module.css";

export const Profile = () => {
  const { account } = useAccount();

  if (!account) return <Navigate to="/" />;

  return (
    <div className={`card ${styles.wrapper}`}>
      <div className="avatar is-size-x-large">
        <span className="icon-user" />
      </div>
      <h1 className="heading-level-5">{account?.name}</h1>
      <Link
        to="/"
        className="button is-secondary u-margin-block-start-16"
        type="button"
      >
        Go back
      </Link>
    </div>
  );
};
